version: '3'

services:
  dev:
    build:
      context: .
    volumes:
      - ./app:/app
    command: python app.py

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./app:/app
    command: pytest
